name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.1

permissions:
  contents: write
  actions: read

jobs:
  release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build frontend
      run: npm run build
      
    - name: Install production dependencies only
      run: npm ci --omit=dev
      
    - name: Install electron-builder temporarily
      run: npm install electron-builder@26.0.12 --no-save
      
    - name: Build Electron app
      run: npx electron-builder
      
    - name: List built files
      run: ls -la dist/
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/Movlex-League-Recorder-*-arm64.dmg
          dist/Movlex-League-Recorder-*-arm64-mac.zip
        generate_release_notes: true
        draft: false
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/
